# Generated by Django 3.0.6 on 2020-05-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200523_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='FK_Sub_Category',
            new_name='FK_Shop',
        ),
    ]
