# Generated by Django 3.0.6 on 2020-05-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200524_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
